title: yamatanooroch's Homepage
page-top-title: Zzz
top-section-bg-text: Clouds veil the crescent moon.
home-subtitle: yamatanooroch &ensp;|&ensp;
copyright-text: '&copy; Zzz 2025-. All Rights Reserved.'
site_name: "=͟͟͞͞(   -ω- )"
site_description: "CS"
email: "3583818830@qq.com"